### ISSUE TITLE
There are identical sub-expressions to the left and to the right of the and operator

### ISSUE THREAD

**Issue by thehlopster** [fsmosca/Lakas#10]
https://github.com/fsmosca/Lakas/blob/26bf45eafac63ea274822cb07ae7242b98515085/tourney_manager/duel/duel.py#L529-L531
The `and` operator is surrounded by identical subexpressions `draw_option['movenumber']`
looks like a typo and probably should be replaced with:
```py
if (draw_option['movenumber'] is not None and draw_option['score'] is not None): 
```

**Comment by fsmosca** [comment]
Thanks will fix it.
