### ISSUE TITLE
fixed time per move

### ISSUE THREAD

**Issue by ChrisWhittington** [fsmosca/Lakas#2]
Hi Ferdy,

Is it possible to ask for a fixed time to move option? Probably I am being dumb, but I can't manage to set anything other then a depth limit, when I'ld prefer to set something like movetime=0.01

Tx if possible.

**Comment by fsmosca** [comment]
Yes I will add it.

**Comment by ChrisWhittington** [comment]
Thanks. A few more things:

concurrency 50 on a 64 core machine seems to work ok.

setting depth=8 and base_time=120 caused  a few problems, several divide by zero reports from python (divide by num_games, line 192, and several games per run were marked as incomplete). I tried increasing the base _time, but there is still the problem. This was with my engine, so it may be my fault.

SF example batchfile is missing set epd status.

**Comment by fsmosca** [comment]
`divide by zero` is due to no games finished are found.

Try your engine with cutechess-cli, see if there are issues with the games. Lakas is powered by cutechess-cli. High threads and fast TC seemed to be problematic with the cutechess-cli.

The batch file is now fixed, thanks.

**Comment by fsmosca** [comment]
[Branch is updated v0.25.0](https://github.com/fsmosca/Lakas/commits/more_logging) to handle movetime.

`--move-time-ms 100`

Note the timemargin of cutechess is set to 50ms by lakas hard-code, engine is not allowed to exceed this additional margin.

Tested with stockfish at `--move-time-ms 100` without time forfeit.
