### ISSUE TITLE
EPD test suite

### ISSUE THREAD

**Issue by ChrisWhittington** [fsmosca/Lakas#4]
are the EPDs taken randomly or serially from ogpt_chess_startpos.epd? (ie same positions for each budget or random?)

are the games back to back (eg one side plays black, then reverse colours same epd?)

**Comment by fsmosca** [comment]
> are the EPDs taken randomly or serially from ogpt_chess_startpos.epd? (ie same positions for each budget or random?)

It is random per budget. `order=random`
https://github.com/fsmosca/Lakas/blob/de04653e09ab40fc9087b0a06201fc68d7c508f3/lakas.py#L346

It can happen that a position in one budget may appear again in another budget.

> are the games back to back (eg one side plays black, then reverse colours same epd?)

Yes, `repeat 2`
https://github.com/fsmosca/Lakas/blob/de04653e09ab40fc9087b0a06201fc68d7c508f3/lakas.py#L343

**Comment by fsmosca** [comment]
This change is now in master.
