### ISSUE TITLE
Feature request: Fixed nodes per move

### ISSUE THREAD

**Issue by Matthies** [fsmosca/Lakas#7]
I would really like to see support for cutechess "nodes=N" mode in Lakas.

Reason:
I found out that training with a fixed depth doesn't work. With fixed depth training I always get parameter sets where the engines runs in a lot of fail-high/fail-lows (which gives many nodes while staying inside the max depth) while playing real games with real time control with this parameter set you just don't get the needed depth and fail badly.

I could believe that training with fixed nodes works better while still avoiding real time controls and the related inaccuracy by CPU load etc.

**Comment by fsmosca** [comment]
There is new v0.29.2 that support [--nodes](https://github.com/fsmosca/Lakas/commit/c93b49ad92e36cc36651898245fad50387658755). It also supports float param values. --hash is now removed. Hash setting can be done in --common-param.

**Comment by Matthies** [comment]
Great! Will test soon. Thanks.

**Comment by Matthies** [comment]
Seems to work as expected.
